### ISSUE TITLE
On mobile while scrolling on rating element triggers onChange with NaN value

### ISSUE THREAD

**Issue by laimonas** [ProntoPro/react-rating#36]
1. Operating system: Windows 10
2. Browser and version (if relevant): chrome 64

### Steps to Reproduce
1. Open chrome browser in mobile emulation mode
2. Add rating
3. Scroll page on rating element
4. Previous rating value lost

**Comment by mavimo** [comment]
@laimonas can you share an example with reproducible issue on codepen or something similar? I try to reproduce it on [demo page](https://prontopro.github.io/react-rating/) but I'm not able to reproduce the reported issue.
